---
title: "projetc_Mia"
format: html
---

```{r}
library(tidyverse)
library(car)
library(dplyr)
library(survival)
library(survminer)
library(zoo) # na.locf

library(janitor)
library(skimr)

library(tableone)

library(tableone)
library(gtsummary)
```

```{r}
METABRIC_RNA_Mutation <- read.csv("METABRIC_RNA_Mutation.csv")
dat0 <- METABRIC_RNA_Mutation %>%
  as_tibble()

dat1 <- dat0 %>%
  transmute(
    patient_id,
    er_status,
    hormone_therapy,
    chemotherapy,
    os_months = overall_survival_months,
    os_event = overall_survival,
    
    age = age_at_diagnosis,
    tumor_size,
    nodes_positive = lymph_nodes_examined_positive,
    grade = neoplasm_histologic_grade,
    her2 = her2_status,
    pam50 = `pam50_._claudin.low_subtype`,
    tumor_stage,
    menopausal_state = inferred_menopausal_state,
    pr_status,
    surgery = type_of_breast_surgery,
    radio_therapy,
    
    tsc2,
    bbc3,
    sbno1,
    ptprd_mut,
    nek1_mut,
    mapk14,
    kmt2c
  )
```
```{r}
dat2 <- dat1 %>%
  mutate(
    across(where(is.character), ~ na_if(.x, "")),
    across(c(er_status, hormone_therapy, chemotherapy,
             grade, her2, pam50, tumor_stage,
             menopausal_state, pr_status, surgery, radio_therapy), as.character),
    across(c(age, tumor_size, nodes_positive, os_months, os_event,
             tsc2, bbc3, sbno1, mapk14, kmt2c), as.numeric)
  )
```

Testing the Proportional Hazards Assumption

```{r}
table(dat_clin$chemotherapy, useNA = "ifany")
table(dat_clin$grade, useNA = "ifany")
table(dat_clin$tumor_stage, useNA = "ifany")
table(dat_clin$pam50, useNA = "ifany")
```

```{r}
library(dplyr)
library(survival)
library(survminer)

# 1. Restrict to ER+ patients receiving hormone therapy
dat_clin <- dat2 %>%
  filter(
    er_status == "Positive",
    hormone_therapy == "1"
  )

# 2. Keep complete cases for variables used in the clinical Cox model
dat_clin <- dat_clin %>%
  filter(
    !is.na(os_months),
    !is.na(os_event),
    !is.na(chemotherapy),
    !is.na(age),
    !is.na(tumor_size),
    !is.na(nodes_positive),
    !is.na(grade),
    !is.na(tumor_stage),
    !is.na(pam50)
  )

# 3. Recode variables
dat_clin <- dat_clin %>%
  mutate(
    grade = factor(grade),

    # Merge tumor stage
    stage_grp = case_when(
      tumor_stage == "1" ~ "I",
      tumor_stage == "2" ~ "II",
      tumor_stage %in% c("3", "4") ~ "III+",
      TRUE ~ NA_character_
    ),

    # Merge PAM50
    pam50_grp = case_when(
      pam50 %in% c("LumA", "LumB") ~ pam50,
      TRUE ~ "Other"
    )
  ) %>%
  mutate(
    stage_grp = factor(stage_grp, levels = c("I", "II", "III+")),
    pam50_grp = factor(pam50_grp, levels = c("LumA", "LumB", "Other"))
  ) %>%
  filter(!is.na(stage_grp), !is.na(pam50_grp))
```
```{r}
table(dat_clin$chemotherapy, useNA = "ifany")
table(dat_clin$grade, useNA = "ifany")
table(dat_clin$stage_grp, useNA = "ifany")
table(dat_clin$pam50_grp, useNA = "ifany")
```
```{r}
cox_clin <- coxph(
  Surv(os_months, os_event) ~
    chemotherapy +
    age +
    tumor_size +
    nodes_positive +
    grade +
    stage_grp +
    pam50_grp,
  data = dat_clin,
  ties = "breslow"
)

summary(cox_clin)
```
```{r}
ph_test <- cox.zph(cox_clin)
ph_test
```
```{r}
event.times <- sort(unique(dat_clin$os_months[dat_clin$os_event == 1]))
event.times <- event.times[-1]

dat_split <- survSplit(
  data = dat_clin,
  cut = event.times,
  end = "os_months",
  start = "t0",
  event = "os_event"
)

dat_split <- dat_split %>%
  mutate(
    chemo_num = as.numeric(chemotherapy),
    chemo_t = chemo_num * log(os_months)
  )

```
```{r}
cox_td <- coxph(
  Surv(t0, os_months, os_event) ~
    chemo_num +
    chemo_t +
    age +
    tumor_size +
    nodes_positive +
    grade +
    stage_grp +
    pam50_grp,
  data = dat_split,
  ties = "breslow"
)

summary(cox_td)
```


